server:
  port: 80


eureka:
  client:
    #是否将自身注册进EurekaServer 默认为true
    register-with-eureka: true
    #是否从EurekaServer获取已有的注册信息，集群环境必须为true才能配合Ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eurekaserver7001:7001/eureka,http://eurekaserver7002:7002/eureka
spring:
  application:
    name: cloud-order-service